### ISSUE TITLE
Discussion: "environment" nomenclature in the documentation is confusing

### ISSUE THREAD

**Issue by brindy** [takeoff-env/takeoff#47]
For me an environment is "production", "staging", etc.  

When I ran `takeoff init <env>` I was expecting it to be structured in a way that reflected this and allow me to add alternative environments based on the same overall source code, but it seems to be more of a "workspace", ie a collection of projects and configuration. 

Further more, the Angular app itself appears to talk about environments, including the code:

```
if (environment.production) {
  enableProdMode();
}
```

Have I misunderstood the intention or would an alternative name (like "workspace") be more appropriate?

**Comment by tanepiper** [comment]
@brindy Yes, I agree I didn't always like that name - workspace does sound better.  Naming is hard :)
