### ISSUE TITLE
remove CODE_OF_CONDUCT, fork into separate project 'takeoff-social'

### ISSUE THREAD

**Issue by Yzrsah** [takeoff-env/takeoff#51]
Hello, I cannot use software dependencies which require HR and legal confirmations outside of the standard license files.

Please consider to fork the project into a separate 'takeoff-social' which can contain a version of takeoff with the added non-code materials and social policies for people working on the takeoff project.

**Comment by tanepiper** [comment]
Hi @Zyrsha thanks for your request, however I won't be removing the code of conduct, nor forking the project to provide this.  This software is released as-is and the CoC does not preclude the use of the software, only submissions and pull requests by contributors and maintainers.
